Remove the codacy badge from README.md
JustinBoehnen/ScalaMatrixLibrary pull request #2
Opened 2023-08-30 21:57 UTC by mengistristen

I propose removing the codacy badge from the README as we no longer care about code quality.

2023-10-29 05:49 UTC, mengistristen commented
Is this project no longer maintained? This pull request has been sitting in limbo for months.

2025-01-14 19:20 UTC, boehnen requested changes
Please renew this codacy app, our codacy score was **_`bussin`_**

2025-01-14 19:21 UTC, boehnen commented
If, on renewal, our score is in fact not **_`bussin`_**, I will approve this PR because that's embarrassing

2025-01-14 19:23 UTC, mengistristen commented
I'm interested in using a more ethically-sourced code quality tool. Just merge the PR.

2025-01-14 19:24 UTC, boehnen commented
> I'm interested in using a more ethically-sourced code quality tool. Just merge the PR.

but the code in the bag ahh

2025-01-14 19:25 UTC, merged